name: Build on openSuse

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 9 4 *'  # every year's 04-09 (April 9th)
    
  
  workflow_dispatch:

  push:
    branches:
      - ci
           
jobs:
  my_first_job_id:
    name: My first job
    runs-on: ubuntu-20.04
    steps:
    - name: Job's checkout
      uses: actions/checkout@master
      
    - name: Show some info and switch branch
      run: |
        uname -a
        cat /etc/os-release
        pwd
        ls -la
        git branch -a
        git fetch origin main
        git branch -a
        git config user.name bot
        git config user.email bot@github.bot.none
        git config --list
        env
        dpkg --list
        df -Th
        mount
        echo $$
        ps axfj
        cat /proc/cpuinfo
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.*'
        host: 'linux'
        target: 'desktop'
#          dir: ${{ github.workspace }}/qt/
        archives: "qtbase qtsvg"
        setup-python: 'false'

    - name: Show info after install Qt6
      run: |
        dpkg --list
        df -Th

    - name: Show files after install Qt 6
      run: |
        find /

