name: test upload artifact

on:

  
  workflow_dispatch:

  push:
    branches:
      - ci
           
jobs:
  test_upload_artifact:
    name: test upload artifact
    runs-on: ubuntu-20.04
    steps:
    - name: git checkout
      uses: actions/checkout@master
      
    - name: Show some info
      run: |
        uname -a
        cat /etc/os-release
        pwd
        ls -la
        git branch -a
        git fetch origin binaries
        git branch -a
        git config user.name bot
        git config user.email bot@github.bot.none
        git config --list
        env
        dpkg --list
        df -Th
        mount
        echo $$
        ps axfj
        cat /proc/cpuinfo
        

    - name: make needed  files
      run: |
        pwd
        mkdir _out_
        mkdir _AppDir_
        mkdir -p _out_/subd
        touch file_1.txt file_2.txt file_3.txt
        echo "hello" >> file_1.txt
        echo "_out_ _out_ _out_" > _out_/out3.txt
        echo "haha" > _AppDir_/haha.txt
        echo "sss" > _out_/subd/s.txt
        find .


        
    - name: upload artiface
      uses: actions/upload-artifact@v3
      with:
        name: built_on_ubuntu-lts
        path: $GITHUB_WORKSPACE/
        
        
        
        
        
        
        
        
        
        
